Pedidos/Models/ErrorViewModel.cs
namespace Pedidos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pedidos/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pedidos.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Linea()
        {
            ViewBag.xValues = new List<int>{50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150};
            ViewBag.yValues = new List<int> { 7, 8, 8, 9, 9, 9, 10, 11, 14, 14, 15 };

            return View();
        }

        public IActionResult Barra()
        {
            return View();
        }

        public IActionResult Pastel()
        {
            return View();
        }

        public FileResult DownloadPdf()
        {
            var filBytes = System.IO.File.ReadAllBytes(@"C:\Users\Cadhe\Downloads\Liga.txt");
            string fileName = "Graficas.pdf";
            return File(filBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        [HttpPost]
        public JsonResult Data()
        {
            var xValues = new List<string> { "Italy", "France", "Spain", "USA", "Argentina" };
            var yValues = new List<int> { 55, 49, 44, 24, 15 };
            var barColors = new List<string> { "#b91d47", "#00aba9", "brown", "#e8c3b9", "#1e7145" };

            var lst = new
            {
                xValues,
                yValues,
                barColors,
            };

            return Json(lst);


        }
    }
}

Pedidos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pedidos.Models;
using System.Diagnostics;

namespace Pedidos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            TempData["Llave1"] = "La llave 1";
            ViewData["Llave2"] = "La llave 2";
            ViewBag.Llave = "La llave 3";

            return View();
        }

        public IActionResult Privacy()
        {

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pedidos/Views/Demo/Barra.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="panel">
<canvas id="myChart" style="width:100%;max-width:600px"></canvas>
</div>

<script type="text/javascript">
$(document).ready(function() {
    document.getElementById("panel").setAttribute("data-pdf", "GraficaBarra.pdf");
    document.getElementById("panel").setAttribute("data-titulo", "Grafica de Barra");
});

var xValues = ["Italy", "France", "Spain", "USA", "Argentina"];
var yValues = [55, 49, 44, 24, 15];
var barColors = ["red", "green","blue","orange","brown"];

new Chart("myChart", {
  type: "bar",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    legend: {display: false},
    title: {
      display: true,
      text: "World Wine Production 2018"
    }
  }
});
</script>

Pedidos/Views/Demo/Linea.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="panel">
<canvas id="myChart" style="width:100%;max-width:600px"></canvas>
</div>

<script type="text/javascript">
    $(document).ready(function() {
    document.getElementById("panel").setAttribute("data-pdf", "GraficaLinea.pdf");
    document.getElementById("panel").setAttribute("data-titulo", "Grafica de Lineas");
});

var xValues = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.xValues))');
var yValues = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.yValues))');;

new Chart("myChart", {
  type: "line",
  data: {
    labels: xValues,
    datasets: [{
      fill: false,
      lineTension: 0,
      backgroundColor: "rgba(0,0,255,1.0)",
      borderColor: "rgba(0,0,255,0.1)",
      data: yValues
    }]
  },
  options: {
    legend: {display: false},
    scales: {
      yAxes: [{ticks: {min: 6, max:16}}],
    }
  }
});
</script>

Pedidos/Views/Demo/Pastel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="panel">
<canvas id="myChart" style="width:100%;max-width:600px"></canvas>

</div>

<script type="text/javascript">
$(document).ready(function() {
    document.getElementById("panel").setAttribute("data-pdf", "GraficaPastel.pdf");
    document.getElementById("panel").setAttribute("data-titulo", "Grafica de Pastel");

    GenericSend('/Demo/Data',null,graficGenerator)
});

//Resultado se obtiene desde el servidor
function graficGenerator(result) {
    new Chart("myChart", {
      type: "pie",
      data: {
        labels: result.xValues,
        datasets: [{
          backgroundColor: result.barColors,
          data: result.yValues
        }]
      },
      options: {
        title: {
          display: true,
          text: "World Wide Wine Production 2018"
        }
      }
    });
}
</script>

Pedidos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pedidos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pedidos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pedidos.styles.css" asp-append-version="true" />
  
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="~/js/GeneralFunctions.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.min.js"></script>  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pedidos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Demo" asp-action="Linea">Linea</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Demo" asp-action="Barra">Barra</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Demo" asp-action="Pastel">Pastel</a>
                        </li>
                    </ul>
                    <form class="form-check-inline my-2 my-lg-0">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="button" id="descargaPDF">Descarga</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pedidos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript">
        setupDownload();
    </script>
</body>
</html>